apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21000
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: services
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 21000
    targetPort: 21000
    name: ftps-pasv
